"use client";

import { PageWrapper } from "@/components/PageWrapper";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <PageWrapper className="flex flex-col min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16 w-full flex-1">
        <Link href="/">
          <Button variant="ghost" className="mb-8 pl-0">
            <ArrowLeft className="w-5 h-5 mr-2" /> Back to Home
          </Button>
        </Link>
        
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
        <p className="text-neutral-500 mb-12">Last Updated: October 2023</p>

        <div className="prose prose-invert max-w-none text-neutral-300">
          <p className="mb-6">
            Welcome to Notiq AI. By accessing or using our website and services, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions, then you may not access the service.
          </p>

          <h3 className="text-xl font-semibold text-white mt-8 mb-4">1. Use of the Service</h3>
          <p className="mb-4">
            Notiq AI provides an AI-powered platform for generating educational materials. You agree to use the service only for lawful purposes and in accordance with these Terms. You are responsible for ensuring that any notes or documents you upload do not violate copyright laws or institutional academic integrity policies.
          </p>

          <h3 className="text-xl font-semibold text-white mt-8 mb-4">2. User Accounts</h3>
          <p className="mb-4">
            To use certain features of the service, you may be required to register for an account. You must provide accurate and complete information and keep your account credentials secure. You are entirely responsible for all activities that occur under your account.
          </p>

          <h3 className="text-xl font-semibold text-white mt-8 mb-4">3. Intellectual Property</h3>
          <p className="mb-4">
            The service and its original content, features, and functionality are owned by Notiq AI and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws. You retain full ownership of the original text and notes you upload to the platform.
          </p>

          <h3 className="text-xl font-semibold text-white mt-8 mb-4">4. AI-Generated Content Disclaimer</h3>
          <p className="mb-4">
            The study materials (flashcards, quizzes, summaries) provided by Notiq AI are generated by artificial intelligence. While we strive for high accuracy, we do not guarantee that the generated content is 100% accurate, complete, or suitable for your specific exams. You should always verify critical information against your original coursework.
          </p>

          <h3 className="text-xl font-semibold text-white mt-8 mb-4">5. Contact Information</h3>
          <p className="mb-4">
            If you have any questions about these Terms, please contact us at: <a href="mailto:wayden2025@gmail.com" className="text-brand-cyan hover:underline">wayden2025@gmail.com</a>
          </p>
        </div>
      </div>
    </PageWrapper>
  );
}
